### ISSUE TITLE
知乎app经常出现"加载失败""请重新加载"

### ISSUE THREAD

**Issue by YaphetS911** [lhie1/Rules#101]
系统：ios12
软件：shadowrocket 2.1.23
规则已更新到最新，证书也没有问题，使用知乎app的时候，经常性出现"加载失败，点击重新加载"等情况。虽然点击后重新加载一下内容就可以正常下载了，但是很影响体验，希望能够修复，谢谢！

**Comment by lhie1** [comment]
问了一下，排除普遍现象，重新安装证书并信任就行了

**Comment by foisonocean** [comment]
@lhie1 
我也遇到了同样的问题，同样是 iOS12 + shadowrocket，试过重装证书并没有用。
