### ISSUE TITLE
阿里通信被完全屏蔽

### ISSUE THREAD

**Issue by hellokitenzihn** [lhie1/Rules#102]
您好，阿里通信App在打开VPN模式中不能正常登陆。烦请测试解决一下。删除了很多关于Ali和淘宝的规则但是还没有用。麻烦啦！

**Comment by lhie1** [comment]
此 App 太久没更新，导致了兼容问题，和规则没什么关系

**Comment by lhie1** [comment]
使用的时候需要关闭相关代理功能
