### ISSUE TITLE
建议删除对 maven.org 的直连规则

### ISSUE THREAD

**Issue by CloudnuY** [lhie1/Rules#131]
`maven.org`、`repo*.maven.org` 均解析到国外IP，国内访问较慢，建议走代理

https://github.com/lhie1/Rules/blob/0e79ae36ed0a3cca217870f5b4ca5df2a7b901f5/Auto/DIRECT.conf#L191
https://github.com/lhie1/Rules/blob/328b986ef5f3ee1af2e076be509bd722495d6ff1/Surge3/domestic.list#L160
https://github.com/lhie1/Rules/blob/0435ce9b9fa76bed7fa7763dad8fe7a98b7f7862/Shadowrocket.conf#L9547

**Comment by lhie1** [comment]
已处理，谢谢
