### ISSUE TITLE
单独给出一份不带REJECT的Quantumult规则可以吗

### ISSUE THREAD

**Issue by Fezreal** [lhie1/Rules#134]
![image](https://user-images.githubusercontent.com/6703674/48748820-29d62000-ecb3-11e8-8f20-747ce5034d0e.png)
就是这份规则，想去掉里面REJECT部分，不想要去广告哈。

我可以手动去掉，但是以后每次更新时都要手动搞一次，不是很方便。

**Comment by lhie1** [comment]
不需要 REJECT 规则使用自带的就行了
