### ISSUE TITLE
Mac Surge 3 内置规则集与apple.list有重复项

### ISSUE THREAD

**Issue by haokaiyang** [lhie1/Rules#135]
版本:Mac Surge 3.0.4
系统内置规则集:
USER-AGENT *com.apple.mobileme.fmip1
USER-AGENT *WeatherFoundation*
USER-AGENT %E5%9C%B0%E5%9B%BE*
USER-AGENT %E8%AE%BE%E7%BD%AE*
USER-AGENT com.apple.geod*
USER-AGENT com.apple.Maps
USER-AGENT FindMyFriends*
USER-AGENT FindMyiPhone*
USER-AGENT FMDClient*
USER-AGENT FMFD*
USER-AGENT fmflocatord*
USER-AGENT geod*
USER-AGENT locationd*
USER-AGENT Maps*
DOMAIN api.smoot.apple.com
DOMAIN captive.apple.com
DOMAIN configuration.apple.com
DOMAIN guzzoni.apple.com
DOMAIN smp-device-content.apple.com
DOMAIN xp.apple.com
DOMAIN-SUFFIX ess.apple.com
DOMAIN-SUFFIX push-apple.com.akadns.net
DOMAIN-SUFFIX push.apple.com
DOMAIN aod.itunes.apple.com
DOMAIN mesu.apple.com
DOMAIN api.smoot.apple.cn
DOMAIN gs-loc.apple.com
DOMAIN mvod.itunes.apple.com
DOMAIN streamingaudio.itunes.apple.com
DOMAIN-SUFFIX lcdn-locator.apple.com
DOMAIN-SUFFIX lcdn-registration.apple.com
DOMAIN-SUFFIX ls.apple.com
PROCESS-NAME trustd
 

经过对比去重后,只剩下
USER-AGENT,AppStore*
USER-AGENT,com.apple.appstored*
USER-AGENT,TestFlight*
DOMAIN-SUFFIX,apple.com
DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,itunes.com
DOMAIN-SUFFIX,me.com
DOMAIN-SUFFIX,mzstatic.com

**Comment by xlighting2017** [comment]
这个是怎么去重的？
假如浏览器打开   support.apple.com  , 按照上面的规则 和下面 的规则， 判定就不同了吧

**Comment by haokaiyang** [comment]
> 这个是怎么去重的？
> 假如浏览器打开 support.apple.com , 按照上面的规则 和下面 的规则， 判定就不同了吧
只去除了相同的规则

**Comment by lhie1** [comment]
apple.list 暂时没有使用，我暂时留下用来转换给 Surge2 使用的
