### ISSUE TITLE
规则不统一

### ISSUE THREAD

**Issue by abingx** [lhie1/Rules#139]
surge规则里onedrive是Proxy，quan里面onedrive是Domestic

**Comment by lhie1** [comment]
Quantumult 的问题请上tg联系 @JackY

**Comment by abingx** [comment]
我意思的在surge的规则里OneDrive划分到了Proxy这个group里
在quan划分到了Domestic这个group里

**Comment by shigalin** [comment]
看样子你没明白这个项目的圈的规则和圈规则的订阅功能
你肯定使用JS之类的脚本，按照正常圈本身的功能这个微软相关的服务是可选策略的
如果是用Fndroid大佬脚本的话，请在https://t.me/Rules_lhie1寻求帮助
