### ISSUE TITLE
公司有内部dns，看dashboard是走的direct，为何还是有代理？

### ISSUE THREAD

**Issue by luanwulin** [lhie1/Rules#140]
这是浏览器的截图，还是有代理

![image](https://user-images.githubusercontent.com/16553854/49061326-670a5700-f24b-11e8-9b9c-7c76c3ef9e0f.png)

这是dashboard的截图
![image](https://user-images.githubusercontent.com/16553854/49058175-d416f000-f23d-11e8-99f9-9f8d4a840f9c.png)

**Comment by xlighting2017** [comment]
这个码打的。。。

如何看出你的浏览器"有代理"?

**Comment by luanwulin** [comment]
@xlighting2017  安全部门查的严，，还是低调点，哈哈。我们内部项目，如果不是内部ip过来的，就会被重定向到一个跳板页面，登陆过后才能回来。

**Comment by luanwulin** [comment]
原来是因为增强模式，，，关掉好了，，，
