### ISSUE TITLE
高德导航开屏广告

### ISSUE THREAD

**Issue by watcthpro** [lhie1/Rules#158]
^https:\/\/m5\.amap\.com\/ws\/valueadded\/.+.

源地址如下
https://m5.amap.com/ws/valueadded/alimama/splash_screen/?ent=2&in=Bnc7TU5kAKMP4kMAcJqoFD12hHY7JzsD%2F0arODTbEr0gAJUVxld2Kizdurfe%2Fbbv9t3BD4c3sAZ%2FtGhCDXvhRzUROM8KoKdAnQIbr5qqvWVtVRXfc%2BAGhHEfYwJ0p1u1%2BN03pkkPKV5orKovyYO741ZIC79lMMKrf%2FvJW1pEbAJ3uPUjHH6SZcFusIHiFQl2mkgiCNjNVgyzQk0jGevqzoZZhQKxqBNyTlCmBxsJllEXmOqNlC4SwuQ%2Bvx4MRZ%2F310q8rIjOmWKx4YonOmaU7j9xNcyMnzNkTiuhZWzjvLK0pnqTumUc4EQBw85YVMvwRyurDTnIUm5XZCzqhyrGO3kBCTqkD6yc25BBuMPF3%2BSZejf2TbINIOZqOXqfnm%2BDwrxANmjUSOAn09S1rj9RMyASYKsdCI27OS8qS%2BcPePBw2EqimpMfJJHkr2spZWM68QGMpAUKC9B09AINL%2Bd0iSbCnDJeKNq9NK4EyDA9cKOSdoR5rYzdL1g%2FZlmGp1VAaAhtq4TUu1YtameCJO1PZz9DByX1dJKLjRj8dbz78QjOmebaImLhUk3CiOXdbCYC78bm4GzqhN5YxpfDUjjvfQ1nQk0sjx0veR5eOo2Z2Nn3dVF7fDryogpzVNZ9SdGe3jjKDRX0UfI%2FFcn2z9a4Qenh0Dyx45s5M%2B4X0UyLTmPHf2HgaN434AwNhMS6dKWfDShNSlRAwlslvAMtMnsHpjdUxf27f9NPapGKcAh7IrBJNWVLfY09Fgiur5t4xTtXsRT3KhcJ4wDNb8gvw1bfvKfTqY1Ic7Ad4twh8e2zgRIhklNLcw7uHWArJ%2BQtzMSUrHlOs2tLQDeD3rMJUGgIf8NvaeifEA1yOUzRLGwGmEQZ7fQkuNipj67C6WSUQ%2BZvu7R35%2FekEAtSGW4YS%2Ba1Xp98ApFRIzVkp35k6Ui9syAUKOAP3IVtDg2idus94h0DB%2FBf9jf9MPIScc2sJ96nh2Pzf9xqS7tupRwNp8iPNUEX5uB1SGr2MF%2Byx%2FShGTEt6uUNAhAOhmJ7FAG39TqQ0ZU3QCyYG2yeFiYToOtEy7H627Q8PSNYQ%2FSYqDC%2BBF6MV8dLzsOY1TRl77xQlmOCW7OgbWH%2FAr3E5Zs6OYNGRD9gmH1o%2BQxhs9S6CSrDWp%2FM&csid=47FB0E6A-408E-4360-B4BF-2CAEB079A702

**Comment by lhie1** [comment]
thx
