### ISSUE TITLE
iPhone 设置->密码与账户->添加账户->Google 无法添加。

### ISSUE THREAD

**Issue by nlnlnull** [lhie1/Rules#182]
更换其他规则是可以添加的，所以节点没有问题，麻烦大佬看一下是不是过度拦截了一些正常的规则。
具体表现为输入完 Google 密码之后，直接就返回到了选择账户的页面，出不来同步选项。

**Comment by nlnlnull** [comment]
通过抓包添加了两条规则解决了。

DOMAIN-SUFFIX,googleadservices.com,🍃 Proxy
DOMAIN-SUFFIX,googleapis.com,🍃 Proxy

不知道会不会和已有规则出现什么冲突，还是麻烦大佬有时间看一下吧。

**Comment by lhie1** [comment]
googleadservices.com 从 reject.list 里面剔除

其他的不需要单独添加规则

**Comment by nlnlnull** [comment]
@lhie1 刚刚测试了一下，只剔除 `googleadservices.com` 并不行。
我是剔除 `googleadservices.com` 并添加`DOMAIN-SUFFIX,googleapis.com,🍃 Proxy`就可以了。

**Comment by nlnlnull** [comment]
> @lhie1 刚刚测试了一下，只剔除 `googleadservices.com` 并不行。
> 我是剔除 `googleadservices.com` 并添加`DOMAIN-SUFFIX,googleapis.com,🍃 Proxy`就可以了。

我是用的 JSBox 的脚本导入的规则。
