### ISSUE TITLE
电报Telegram启动一直loading,登录不上

### ISSUE THREAD

**Issue by alanhg** [lhie1/Rules#183]
![image](https://user-images.githubusercontent.com/9245110/55278764-64c81e80-534b-11e9-82d6-55c4d1158621.png)

**Comment by ydzydzydz** [comment]
> ![image](https://user-images.githubusercontent.com/9245110/55278764-64c81e80-534b-11e9-82d6-55c4d1158621.png)
> 

1. 开启增模式

2. 挂socks5代理: [8888端口](https://t.me/socks?server=127.0.0.1&port=8888&user=&pass=)  [6153端口](https://t.me/socks?server=127.0.0.1&port=6153&user=&pass=)

**Comment by alanhg** [comment]
thanks,我选择开启增强模式，解决了
