### ISSUE TITLE
淘寶提示使用vpn

### ISSUE THREAD

**Issue by MisterGlasses** [lhie1/Rules#186]
![AEBC79D4-CDC1-49AC-AE9F-3C50A1508A7D](https://user-images.githubusercontent.com/27768847/56093266-c4502d80-5ef8-11e9-8cc2-002b3a29771e.png)
![D216CDA5-AEEE-4947-9D42-60DE0AFABC08](https://user-images.githubusercontent.com/27768847/56093267-c4e8c400-5ef8-11e9-8cca-022db2e03012.jpeg)
刪除taobao.com後正常

**Comment by WYBNZB** [comment]
这个取件码是给我的吗?是那个快递?

**Comment by WYBNZB** [comment]
这个取件码是给我的吗?是那个快递?

**Comment by MisterGlasses** [comment]
> 这个取件码是给我的吗?是那个快递?

？？？老哥你在說啥

**Comment by WYBNZB** [comment]
(ಡωಡ) 你发给我的这两个图片是啥?

**Comment by WYBNZB** [comment]
(ಡωಡ) 你发给我的这两个图片是啥?

**Comment by WYBNZB** [comment]
……我好像理解错了，溜了溜了

**Comment by MisterGlasses** [comment]
> (ಡωಡ) 你发给我的这两个图片是啥?

就是圖二從這個地方點進去 會提示使用了代理 從圖一中把淘寶刪除就好了 我現在沒法復現 所以只能發這兩個圖

**Comment by MisterGlasses** [comment]
> ……我好像理解错了，溜了溜了

這。。。我還以為你是開發者呢

**Comment by WYBNZB** [comment]
……我以为你是暗网的商家

**Comment by MisterGlasses** [comment]
可怕

________________________________

**Comment by WYBNZB** [comment]
哈哈哈，溜了溜了，晚安伙计(❁´◡`❁)*✲ﾟ*
