### ISSUE TITLE
误伤所有blog三级域名

### ISSUE THREAD

**Issue by jpacg** [lhie1/Rules#197]
示例：
http://blog.sina.com.cn

Sub-rule matched: URL-REGEX https?://\w+.?(ad(s)?|log\w?|tj|tongji|((?!static)stat\w+?)|\w+?trac(e|k)?|click).\w+
Rule matched: RULE-SET Reject.list
Disconnect with reason: Reject by rule

**Comment by lhie1** [comment]
https://github.com/lhie1/Rules/commit/4fd32e66a46557495e234d9e2b57186eb3a81f29
