### ISSUE TITLE
Auto文件夹和其他部分是什么关系？

### ISSUE THREAD

**Issue by laggardkernel** [lhie1/Rules#215]
最初我以为所有app配置都是从Auto文件夹自动生成的，但根据比较事实并非除此。尽管列表内容类似，但各app配置并不与Auto下对应部分同步。

如果要提交pr，添加新域名规则，应该提交到哪里？

**Comment by lhie1** [comment]
目前都是基于 Surge 3 文件夹里的文件转换同步

**Comment by laggardkernel** [comment]
所以，我提交pr应该修改`Rules/Surge3`文件夹内内容，以此文件夹为准？

另外，`Rules/Auto/DIRECT.conf`与`Rules/Surge3`的内容并不同步，这种情况怎么办呢？

**Comment by lhie1** [comment]
Auto 文件夹暂时是废弃状态，暂未更新
