### ISSUE TITLE
`DOMAIN-SUFFIX,sharethis.com` rule from PROXY.conf, REJECT.conf are in conflict

### ISSUE THREAD

**Issue by laggardkernel** [lhie1/Rules#22]
`DOMAIN-SUFFIX,sharethis.com` occurs in both `Auto/PROXY.conf` and `Auto/REJECT.conf`.

- https://github.com/lhie1/Rules/blob/master/Auto/PROXY.conf#L424
- https://github.com/lhie1/Rules/blob/master/Auto/REJECT.conf#L4307

**Comment by lhie1** [comment]
It's fixed, thank you.
