### ISSUE TITLE
Surge Build1362 使用 lhie1配置，无法正常刷微博

### ISSUE THREAD

**Issue by xieft** [lhie1/Rules#220]
Surge Build1362 使用 lhie1配置，无法正常刷微博
把Surge 切换到1334 就一切正常了。
测试在iOS12 和iOS13 上结果一致
主要表现是无法获取微博和评论。
目前不清楚是脚本不兼容还是Surge的Bug
可以帮忙测试解决一下吗

**Comment by xieft** [comment]
和Surge 团队反映后，确定是脚本的问题

**Comment by lhie1** [comment]
已暂时移除脚本
