### ISSUE TITLE
iOS 添加 Google 账户问题

### ISSUE THREAD

**Issue by Hayxi** [lhie1/Rules#228]
建议添加规则
`AND,((USER-AGENT,%E8%AE%BE%E7%BD%AE*), (DOMAIN-SUFFIX,googleapis.com)),Proxy`

`%E8%AE%BE%E7%BD%AE*` 是「设置」的 USER-AGENT，添加前的表现症状为输入 Google 账号密码后没有任何反应，因为「设置」走的是 `RULE-SET,SYSTEM,DIRECT`，导致 googleapis.com 走直连。

**Comment by Hayxi** [comment]
因为 `RULE-SET,SYSTEM,DIRECT` 的优先级很高，以上这条规格可能需要告知用户自行添加或者默认添加到自定义规则里。

**Comment by lhie1** [comment]
你好，已调整默认规则的优先级
