### ISSUE TITLE
在Google Chrome下，购物党插件无法正常比价

### ISSUE THREAD

**Issue by xieft** [lhie1/Rules#231]
购物党插件地址：https://chrome.google.com/webstore/detail/%E8%B4%AD%E7%89%A9%E5%85%9A%E8%87%AA%E5%8A%A8%E6%AF%94%E4%BB%B7%E5%B7%A5%E5%85%B7/jgphnjokjhjlcnnajmfjlacjnjkhleah?hl=zh-CN

联系购物党客服给了我两个网站测试，第一个无法打开：
https://browser.gwdang.com/ip.php?from_device=default&callback=jQuery111305659550118621262_1542765644383&_=1542765644384
https://cdn.gwdang.com/js/gwdang-notifier.js?v=1535535406761

关掉代理后正常访问

**Comment by lhie1** [comment]
已删除
