### ISSUE TITLE
希望Surge3下的Domestic.list加上校园网的地址

### ISSUE THREAD

**Issue by Seedhope** [lhie1/Rules#252]
现在用的api国内媒体用的是domestic规则，挂着代理连校园网，无法访问校园网登录地址，自己试了下，ip里加上1.1.1.1然后Domestic里加上msftconnecttest.com就能解决这个问题，挂着代理能够正常访问校园网，希望补充上。
1.1.1.1
msftconnecttest.com
![image](https://user-images.githubusercontent.com/47686378/69863448-c88a5900-12d7-11ea-9ebd-8fb5c8e4799c.png)

**Comment by lhie1** [comment]
OK
