### ISSUE TITLE
Shadowrocket 淘宝VPN验证 QQ无法使用位置信息

### ISSUE THREAD

**Issue by xieqing0428** [lhie1/Rules#254]
Shadowrocket PC-使用淘宝/天猫页面出现VPN验证，APP-淘宝直播等使用时显示使用VPN拦截无法访问 APP-QQ无法使用位置信息

**Comment by lhie1** [comment]
未发现此问题

**Comment by xieqing0428** [comment]
？？？ app手机qq点击聊天->位置信息无法使用啊，关闭vpn加载以后再使用位置信息倒是可以，但也估计是缓存，看了下图源是腾讯地图

**Comment by xieqing0428** [comment]
> 未发现此问题

？？？ app手机qq点击聊天->位置信息无法使用啊，关闭vpn加载以后再使用位置信息倒是可以，但也估计是缓存，看了下图源是腾讯地图
