### ISSUE TITLE
dler.cloud托管的规则无法打开notion

### ISSUE THREAD

**Issue by neutron1988** [lhie1/Rules#255]
查了一下之前的规则是把notion.so加入代理的，能否在当前托管规则里面也加入啊？谢谢！

**Comment by lhie1** [comment]
现在也在里面阿

**Comment by neutron1988** [comment]
确实不在，通过Dler Cloud的一键托管链接下载的规则里到现在依然是没有Notion的

**Comment by lhie1** [comment]
DOMAIN-SUFFIX,notion.so

**Comment by neutron1988** [comment]
> [Rules/Surge/Surge 3/Provider/Proxy.list](https://github.com/lhie1/Rules/blob/86c8f3163b5f63d8673adc87ccd08f04180a55ab/Surge/Surge%203/Provider/Proxy.list#L321)
> Line 321 in [86c8f31](/lhie1/Rules/commit/86c8f3163b5f63d8673adc87ccd08f04180a55ab)
>  DOMAIN-SUFFIX,notion.so

呃，现在确实可以了，多谢。最开始发帖的时候，我都是在规则里搜不到notion的
