### ISSUE TITLE
请问为什么要在拦截规则加入libs.baiducom？

### ISSUE THREAD

**Issue by ischengxy** [lhie1/Rules#258]
[规则地址](https://github.com/lhie1/Rules/blob/master/Surge3/Reject.list)由于我使用的一个导航网站它的jQuery是从 **https://libs.baidu.com/jquery/1.9.0/jquery.js?v=18.11** 获取的，现在 **libs.baidu.com** 被拦截了，我想问一下可否还记得当初为什么要拦截此网站吗？

**Comment by lhie1** [comment]
已忘记，不过我暂时先删掉了

**Comment by ischengxy** [comment]
@lhie1 ok
