### ISSUE TITLE
希望把IP-CIDR类型的规则做成可选项，由用户决定是否添加

### ISSUE THREAD

**Issue by vxxholic** [lhie1/Rules#26]
我这边不能正常工作的好几个bug全是这个类型的……

![hrn0vi5dm2obxkzx1bfs_vf4qjaew0bsmcf5sbmsshf78ihht9kbhshyzpmaqm_xpalpkabuwfkmkcs3h6xmxv0xpf2atykpnipxiid_tgpcvx107nd1bcqygk6jlgimr1scyc1dj0ph733zwqkojerp0qafbb5dhmsfjhc7qw60po8vrvgdeif-9ud_5ro5vfzdbctcvfohv-sr1zze](https://user-images.githubusercontent.com/7752687/39034362-aa16bf80-44a8-11e8-9021-371e3764b4b0.png)

![gjm8nunwz3ij6eg3f_nwzugogpxn1nua85uhtk2pchx5vh8lr0l6gqr-tsli16hprmecirkldgst-k2nc8xskfjg_y5ym0wl7bzgk4is5jk9jsfqguwph6pdrmmrsvlzi-nuhf3etv4kexyys60o-nwgdpfyn2kb_fsmqh4l_gd8ivzj_fs9e3lm2r1sgigminp-jnxvxd_vxcfc4gax](https://user-images.githubusercontent.com/7752687/39034367-af5f5dee-44a8-11e8-9160-62e5673e5553.png)

![z3bhuyp__3byxajwazy-gdaw6lsrqu6dxns0fiktom8avcmisbirqrevahgbybkbkdc7wwy5lenwqkbmhia8eijjsxqt3wjegqutkydp5evdfwad6rofyhhhdxvg-c96ubygp2wzbyxvcijms9tdxjsnteclx-yepd6daiprtixsvetb7lffzotwcyvb3-sniozoref3gl584qksp8l_](https://user-images.githubusercontent.com/7752687/39034395-d247d71e-44a8-11e8-94b2-6bad58906600.png)

![j-zfkneuro8bqgwlhhpcldb6gbtgnlf_wwj7o6_w74x4pdhnshqdj25ehbxf99bhogzg0za-9y3lh2pl7iora9cito1pyubb-oel6dwqls9cxnb_cdlprfyqdw6urwrepf8zpaqpvkn3g2yla2ijj5jpyno876ia3hn9rnoaqtxemwhpe0ioy4kiq8dtaejywj71o6pe_sstrwboipa3](https://user-images.githubusercontent.com/7752687/39034372-b671716c-44a8-11e8-83ac-aa300acabaa2.png)

![default](https://user-images.githubusercontent.com/7752687/39034492-224b6f50-44a9-11e8-8d40-0eae3738dc75.png)

C:\WINDOWS\system32>ping 52.6.136.217

正在 Ping 52.6.136.217 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

52.6.136.217 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\WINDOWS\system32>ping 52.20.116.4

正在 Ping 52.20.116.4 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

52.20.116.4 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\WINDOWS\system32>ping 69.171.233.33

正在 Ping 69.171.233.33 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

69.171.233.33 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\WINDOWS\system32>ping 66.220.149.32

正在 Ping 66.220.149.32 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

66.220.149.32 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by lhie1** [comment]
规则里根本没有这些IP阿

// LAN,debugging rules should place above this line
DOMAIN-SUFFIX,local,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,172.0.0.0/12,DIRECT
IP-CIDR,192.168.0.0/16,DIRECT

// TeamViewer
IP-CIDR,109.239.140.0/24,🍂 Domestic,no-resolve
IP-CIDR,139.220.243.27/32,🍂 Domestic,no-resolve
IP-CIDR,172.16.102.56/32,🍂 Domestic,no-resolve
IP-CIDR,185.188.32.1/28,🍂 Domestic,no-resolve
IP-CIDR,221.226.128.146/32,🍂 Domestic,no-resolve

// LINE
IP-CIDR,103.2.28.0/22,🍃 Proxy,no-resolve
IP-CIDR,119.235.224.0/21,🍃 Proxy,no-resolve
IP-CIDR,119.235.232.0/23,🍃 Proxy,no-resolve
IP-CIDR,119.235.235.0/24,🍃 Proxy,no-resolve
IP-CIDR,119.235.236.0/23,🍃 Proxy,no-resolve
IP-CIDR,125.6.146.0/24,🍃 Proxy,no-resolve
IP-CIDR,125.6.149.0/24,🍃 Proxy,no-resolve
IP-CIDR,125.6.190.0/24,🍃 Proxy,no-resolve
IP-CIDR,125.209.208.0/20,🍃 Proxy,no-resolve
IP-CIDR,203.104.103.0/24,🍃 Proxy,no-resolve
IP-CIDR,203.104.128.0/20,🍃 Proxy,no-resolve
IP-CIDR,203.174.66.64/26,🍃 Proxy,no-resolve
IP-CIDR,203.174.77.0/24,🍃 Proxy,no-resolve

// Telegram
IP-CIDR,109.239.140.0/24,🍃 Proxy,no-resolve
IP-CIDR,149.154.160.0/20,🍃 Proxy,no-resolve
IP-CIDR,91.108.4.0/16,🍃 Proxy,no-resolve
IP-CIDR6,2001:67c:4e8::/48,REJECT,no-resolve
IP-CIDR6,2001:b28:f23d::/48,REJECT,no-resolve
IP-CIDR6,2001:b28:f23f::/48,REJECT,no-resolve

// Kakao Talk
IP-CIDR,1.201.0.0/24,🍃 Proxy,no-resolve
IP-CIDR,103.246.56.0/22,🍃 Proxy,no-resolve
IP-CIDR,103.27.148.0/22,🍃 Proxy,no-resolve
IP-CIDR,110.76.140.0/22,🍃 Proxy,no-resolve
IP-CIDR,113.61.104.0/22,🍃 Proxy,no-resolve
IP-CIDR,27.0.236.0/22,🍃 Proxy,no-resolve

**Comment by vxxholic** [comment]
刚刚把User Data 、Rule OTA和Shadowrocket配置文件全部删了重来一遍

在生成的配置文件里测试199.59.150.49，结果仍然是DIRECT

![ahagk_5rkg7hneprd7qy1zru23fc17toqgpmn9cyheb255ijtoxqskqproikhyb2vhezlrny7uar_l9rya7wtqjqgi9gcimlarurdzfdaa3tolva01hdh-re3wvcqqwgg8ki7htiaowk6mlamuylbqjcrla6myxq_bqpl-eqxec4pvum9jxb0jewp5iuw4zffvyomn1s1m9zapumydj6](https://user-images.githubusercontent.com/7752687/39041271-04753634-44bb-11e8-9860-7e39167c53ae.png)

![default](https://user-images.githubusercontent.com/7752687/39041334-25750120-44bb-11e8-8639-7acd9a0ea315.png)

附上配置文件（并没有找到199开头的规则）

[lhie1.db.conf.txt](https://github.com/lhie1/Rules/files/1931419/lhie1.db.conf.txt)

**Comment by lhie1** [comment]
那就说明规则确实没有问题，请从其他地方检查。

**Comment by vxxholic** [comment]
找到规则的问题在哪了，我把
`
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,17.0.0.0/8,localhost,*.local,*.crashlytics.com,::ffff:0.0.0.0/1,::ffff:128.0.0.0/1 `

改成

`skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlytics.com,captive.apple.com `

以后，就不会再出现我一开始提到的那些bug了

**Comment by lhie1** [comment]
@vxxholic 我已经更新了

**Comment by vxxholic** [comment]
“跳过代理”部分好像没更新？至少我在最新版规则下还是能复现一开始提到的那些bug

**Comment by lhie1** [comment]
@vxxholic 🤦‍♂️ 更新了..
