### ISSUE TITLE
建议GlobalTV中加下AppleTV+的规则

### ISSUE THREAD

**Issue by Darren-X1** [lhie1/Rules#261]
# > Apple TV+
 DOMAIN-SUFFIX,tv.apple.com
 DOMAIN-SUFFIX,play-edge.itunes.apple.com
 DOMAIN-SUFFIX,np-edge.itunes.apple.com

**Comment by Darren-X1** [comment]
我试了下它就卡点开播放的瞬间
DOMAIN-SUFFIX,tv.apple.com 可加可不加

**Comment by lhie1** [comment]
OK
