### ISSUE TITLE
有两条规则会影响小米的云同步和小米的流量查询。

### ISSUE THREAD

**Issue by ischengxy** [lhie1/Rules#262]
[规则地址](https://github.com/lhie1/Rules/blob/master/Surge/Surge%203/Provider/Reject.list)
### 两条规则
- **api.sec.miui.com**
-  **pdc.micloud.xiaomi.net**

### 截图
![photo_2020-01-08_12-56-35.jpg](https://i.loli.net/2020/01/08/raqgSQJOnuPvBVc.jpg)
![photo_2020-01-08_12-56-43.jpg](https://i.loli.net/2020/01/08/CjvYMI6mxDuPas5.jpg)

**Comment by lhie1** [comment]
感謝反饋，已修復
