### ISSUE TITLE
macOS issue

### ISSUE THREAD

**Issue by iam3ddy** [lhie1/Rules#268]
when using this rule

> [Host]
ocsp.apple.com = server:127.0.0.1

many app on macOS unable to launch

**Comment by lhie1** [comment]
此规则是我用于屏蔽检测吊销证书用的，请问macOS 上有哪些应无法正常启动？

**Comment by iam3ddy** [comment]
examples:
IINA
Dropbox

**Comment by dabuddha** [comment]
感觉是好多非apple store下的应用，启动都变长了

**Comment by lhie1** [comment]
已删除
