### ISSUE TITLE
希望增加菜鸟裹裹开屏广告拦截 谢谢

### ISSUE THREAD

**Issue by Six9od** [lhie1/Rules#27]
https://itunes.apple.com/us/app/%E8%8F%9C%E9%B8%9F%E8%A3%B9%E8%A3%B9-%E5%BF%AB%E9%80%92%E9%9A%8F%E6%97%B6%E6%9F%A5%E5%AF%84%E5%8F%96/id951610982?mt=8

**Comment by lhie1** [comment]
没看到有广告
