### ISSUE TITLE
支持QuanX

### ISSUE THREAD

**Issue by MvsCode** [lhie1/Rules#283]
可以考虑支持QuanX吗

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ShawCCC** [comment]
quanx已经支持的

**Comment by MvsCode** [comment]
> quanx已经支持的

不太一样

**Comment by shikkoku** [comment]
源码里不是有QuantumultX吗？说明没更新而已吧。

**Comment by MvsCode** [comment]
> 源码里不是有QuantumultX吗？说明没更新而已吧。

配置是指向https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/AdBlock
也就是GeQ1an Fork Hile1规则进行修改，不是Hile1本人维护，没有说哪个好坏，只是本人我更希望Hile1会出一个

**Comment by ShawCCC** [comment]
https://raw.githubusercontent.com/lhie1/Rules/master/Quantumult/QuantumultX.conf

**Comment by MvsCode** [comment]
> https://raw.githubusercontent.com/lhie1/Rules/master/Quantumult/QuantumultX.conf

请教，你用这个链接可以在QuanX用？

**Comment by Chandler-Lu** [comment]
> > 源码里不是有QuantumultX吗？说明没更新而已吧。
> 
> 配置是指向https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/AdBlock
> 也就是GeQ1an Fork Hile1规则进行修改，不是Hile1本人维护，没有说哪个好坏，只是本人我更希望Hile1会出一个

人家名字都打错了还指望人家维护= =

**Comment by MvsCode** [comment]
> > > 源码里不是有QuantumultX吗？说明没更新而已吧。
> > 
> > 
> > 配置是指向https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/AdBlock
> > 也就是GeQ1an Fork Hile1规则进行修改，不是Hile1本人维护，没有说哪个好坏，只是本人我更希望Hile1会出一个
> 
> 人家名字都打错了还指望人家维护= =

抱歉咯，别人有需求，又在那圣母，当作者真去跟进出来，又要用说真香，丑陋的嘴脸

**Comment by Chandler-Lu** [comment]
> > > > 源码里不是有QuantumultX吗？说明没更新而已吧。
> > > 
> > > 
> > > 配置是指向https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/AdBlock
> > > 也就是GeQ1an Fork Hile1规则进行修改，不是Hile1本人维护，没有说哪个好坏，只是本人我更希望Hile1会出一个
> > 
> > 
> > 人家名字都打错了还指望人家维护= =
> 
> 抱歉咯，别人有需求，又在那圣母，当作者真去跟进出来，又要用说真香，丑陋的嘴脸

不好意思了，我自己维护我自己的规则，不用别人的。不会真香

**Comment by MvsCode** [comment]
> > > > > 源码里不是有QuantumultX吗？说明没更新而已吧。
> > > > 
> > > > 
> > > > 配置是指向https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/AdBlock
> > > > 也就是GeQ1an Fork Hile1规则进行修改，不是Hile1本人维护，没有说哪个好坏，只是本人我更希望Hile1会出一个
> > > 
> > > 
> > > 人家名字都打错了还指望人家维护= =
> > 
> > 
> > 抱歉咯，别人有需求，又在那圣母，当作者真去跟进出来，又要用说真香，丑陋的嘴脸
> 
> 不好意思了，我自己维护我自己的规则，不用别人的。不会真香

请不要对号入座哦。没办法啦，我这些菜逼，只能请求别人啦，没你那么吊
