### ISSUE TITLE
Android FCM服务仍被代理

### ISSUE THREAD

**Issue by shikkoku** [lhie1/Rules#284]
原规则DOMAIN-SUFFIX,mtalk.google.com,Domestic
但我实际使用上Android会跳转到类似alt7-mtalk.google.com这样的域名来连接fcm服务，这样会命中DOMAIN-KEYWORD,google,Proxy规则，仍然通过了代理。目前fcm服务中国大陆可以直连。
建议改为domain-keyword mtalk.google,Domestic，这样即使解析到alt7-mtalk.google.com这类型的域名也可以直连fcm服务。

**Comment by lhie1** [comment]
稍后修正

**Comment by shikkoku** [comment]
https://github.com/Kr328/ClashForAndroid/issues/118#issuecomment-589698809_
