### ISSUE TITLE
误杀：知乎热搜显示不出来

### ISSUE THREAD

**Issue by Liquor030** [lhie1/Rules#287]
我看最近请求，是由于Reject.list导致，我把Reject.list设置为DIRECT则恢复正常。

**Comment by lhie1** [comment]
那么具体是触发了哪一条规则可以看看吗？

**Comment by Liquor030** [comment]
好的 我测试看看

**Comment by Liquor030** [comment]
@lhie1 REGEX,https?://api.zhihu.com/(fringe|zst|real_time|ad-style-service|banners|topstory/hot-lists|market/popover|mqtt|me|.*launch|.*featured-comment-ad|search/(top|tabs|preset))
这一条

**Comment by Liquor030** [comment]
GET /search/top_search/tabs/hot/items HTTP/1.1
Host: api.zhihu.com
好像是误杀了这个
