### ISSUE TITLE
错误？：Special.list会导致一些莫名其妙的问题

### ISSUE THREAD

**Issue by Liquor030** [lhie1/Rules#289]
比如：微博屏蔽广告时，导致微博加载缓慢，甚至加载失败，去掉该规则后正常

**Comment by nlnlnull** [comment]
有同样的问题，打开微博 Surge 甚至会断开，Surge 加载 JS 脚本。

**Comment by Liquor030** [comment]
@nlnlnull 我将Special.list删除后正常 你可以尝试一下

**Comment by nlnlnull** [comment]
> @nlnlnull 我将Special.list删除后正常 你可以尝试一下

我直接换了一套规则。😅
