### ISSUE TITLE
建议从domestic移除PayPal

### ISSUE THREAD

**Issue by MarvinHAHA** [lhie1/Rules#291]
直连时登陆美区账号总是报错，切换去proxy就好了

**Comment by lhie1** [comment]
报错是因为你的登录历史IP 问题，我一直直连没有问题，而且经常IP 变动会导致账户风控

**Comment by sukiko789** [comment]
建议额外拉出Paypal组，我也遇到了这个问题，直连不能登录，修改成Proxy可以登录
