### ISSUE TITLE
Mac + Surge作为网关模式导致手淘App搜索功能无法使用

### ISSUE THREAD

**Issue by tanglueyi** [lhie1/Rules#302]
最近我在使用 mac+surge 做网关的模式下（开启了 MitM），手淘 App 打开搜索一个东西就会被弹出正在使用 VPN 的信息导致无法搜索任何东西。我使用的是托管自带的规则并且是规则判定模式出站。起初我以为是 Surge 的问题，但是经过尝试我注意到，只有我把出站模式调整到 Direct 时就不会有问题（关闭 MitM 并不能解决）。

- 2020/3/13 12:01 **补充，FINAL调整成Direct可临时解决此问题。可是这样就等于放弃了访问国外大部分网站的访问速度，因为不走代理了。

### 我出现问题的截图：
![IMG_932551BB772C-1](https://user-images.githubusercontent.com/3315564/76585010-3ae61880-6518-11ea-998f-ee821bcd63ce.jpeg)

### 以下是使用过程中产生的流量信息

- 最近请求

![C9500CFE-EB21-45E3-9F57-CAE017B989E4](https://user-images.githubusercontent.com/3315564/76584882-e5117080-6517-11ea-8cce-2addf6573b45.png)

- 活动请求

![F24D3DF3-131F-4091-8EF0-92CC3212D50D](https://user-images.githubusercontent.com/3315564/76584914-fa869a80-6517-11ea-9fbe-82cc40f4665e.png)

- 我的配置截图

![057EEBB5-DC9D-42CD-AF71-D6D5AABC5C50](https://user-images.githubusercontent.com/3315564/76584931-05412f80-6518-11ea-81b5-771960b883cd.png)

**Comment by xpzouying** [comment]
猜测有2点：
1、淘宝封锁了很多云服务的IP；
2、过滤规则中，有些涉及到淘宝的规则走了代理，导致1的情况触发。

个人感觉某些淘宝的规则没有走DIRECT，而直接掉到FINAL走了代理，可将FINAL规则切换为DIRECT进行验证。

**Comment by tanglueyi** [comment]
> 猜测有 2 点：
> 1、淘宝封锁了很多云服务的 IP；
> 2、过滤规则中，有些涉及到淘宝的规则走了代理，导致 1 的情况触发。
> 
> 个人感觉某些淘宝的规则没有走 DIRECT，而直接掉到 FINAL 走了代理，可将 FINAL 规则切换为 DIRECT 进行验证。

感谢提供建议！
FINAL 调整成 Direct 可临时解决此问题。可是这样就等于放弃了访问国外大部分网站的访问速度，因为不走代理了。

**Comment by lhie1** [comment]
看了一下，这个应该也不是规则的问题，规则里没有将阿里或淘宝的域名指向代理，活动记录里的IP 都被自动指向了`FINAL`

参阅资料：https://community.nssurge.com/d/6-dhcp-surge-router-mode/5
