### ISSUE TITLE
Microsoft 规则有误

### ISSUE THREAD

**Issue by God-2333** [lhie1/Rules#304]
有误规则：`DOMAIN-KEYWORD,microsoft`

造成一些域名中含有Microsoft 的域名也代理

举例：世纪互联 OneDrive 域名 `microsoftonline.cn`
(目前就发现这么一个，可能改成 microsoft.com 会比较好？)

**Comment by lhie1** [comment]
我在前面新增一条`DOMAIN-SUFFIX,cn,DIRECT`吧，感觉Microsoft 的太难处理了..
