### ISSUE TITLE
services.googleapis.cn使用Direct导致连接问题

### ISSUE THREAD

**Issue by cokecodecock** [lhie1/Rules#310]
国行Android设备上Google框架请求的services.googleapis.cn使用Direct策略会影响Google服务的使用。
通过查看Clash的log发现，目前DlerCloud使用的默认托管规则中会出现`services.googleapis.cn match DomainSuffix using DIRECT` 从而影响Google服务的使用。

**Comment by xlighting2017** [comment]
@lhie1  在 这一行
`- DOMAIN-SUFFIX,cn,DIRECT`

前面加一行, 变成
```
- DOMAIN-SUFFIX,googleapis.cn,Proxy
- DOMAIN-SUFFIX,cn,DIRECT
```

**Comment by lhie1** [comment]
已解决
