### ISSUE TITLE
建议把Apple的IP-CIDR加入Apple.list

### ISSUE THREAD

**Issue by DeltaXrayDelta** [lhie1/Rules#318]
有些Apple的服务，不是用域名连接的，而是直接使用Geo-IP归属地在海外的IP地址，无法被Domain规则Geo-IP=CN 规则匹配到，可能导致本该使用直连的连接走了代理

数据来源：AS714 Apple Inc.

https://raw.githubusercontent.com/DeltaXrayDelta/IT/master/Internet/apple_ip_rule.list

**Comment by lhie1** [comment]
添加这个的意义是啥？

**Comment by DeltaXrayDelta** [comment]
有些Apple的服务，不是用域名连接的，而是直接使用Geo-IP归属地在海外的IP地址，无法被Domain规则Geo-IP=CN 规则匹配到，可能导致本该使用直连的连接走了代理

**Comment by DeltaXrayDelta** [comment]
> 添加这个的意义是啥？


有些Apple的服务，不是用域名连接的，而是直接使用Geo-IP归属地在海外的IP地址，无法被Domain规则Geo-IP=CN 规则匹配到，可能导致本该使用直连的连接走了代理。

**Comment by lhie1** [comment]
@DeltaXrayDelta 目前还没有发现有哪些Apple 的服务没有使用域名连接，请问有相关程序或数据吗？

**Comment by DeltaXrayDelta** [comment]
> @DeltaXrayDelta 目前还没有发现有哪些Apple 的服务没有使用域名连接，请问有相关程序或数据吗？

刚抓了个包，FaceTime 视频/音频都是通过UDP协议直连位于美国的IP地址，没有使用域名

![image](https://user-images.githubusercontent.com/53411520/77502614-4b8e7b00-6e96-11ea-8043-47197f64663a.jpeg)
![image](https://user-images.githubusercontent.com/53411520/77502619-51845c00-6e96-11ea-8a6f-c8a651e5fc90.png)

**Comment by zyyz2450** [comment]
你可以自己加一条geoip，参数为us

**Comment by DeltaXrayDelta** [comment]
> 你可以自己加一条geoip，参数为us

Geo-IP = US 误命中率太大，还是有针对性地分流 Applw 的服务比较好

**Comment by lhie1** [comment]
感谢，已添加
