### ISSUE TITLE
Auto/URL Rewrite.conf中部分规则阻止YouTube去广告script功能

### ISSUE THREAD

**Issue by vhvg** [lhie1/Rules#332]
![image](https://user-images.githubusercontent.com/14148813/78365422-aab86200-75f1-11ea-8dee-fe4b3c00561f.png)
上图为Auto/URL Rewrite.conf中有关YouTube部分去广告规则，划线两条规则在启用时会阻止https://Choler.github.io/Surge/Script/YouTube.js提供的去广告功能。
测试中，在保留上述两条规则时，YouTube客户端表现为，5秒广告期间黑屏，5秒钟后自动跳过。
去掉上述两条规则时，YouTube去广告script生效，YouTube客户端表现为可以直接跳过5秒钟广告，立即开始播放视频。

因此请求删去这两条规则：
`
^https?://.+.googlevideo.com/.+&oad - reject   
^https?://.+.googlevideo.com/.+ctier - reject    
`

**Comment by lhie1** [comment]
OK
