### ISSUE TITLE
误杀bilibili游戏服务器

### ISSUE THREAD

**Issue by kokororin** [lhie1/Rules#340]
![195A75AC-7ADA-438A-9B81-9548EAF96D46](https://user-images.githubusercontent.com/10093992/78846444-5fadad00-7a3e-11ea-936b-17b42e52c3eb.png)

08:56:08.311719 Sub-rule matched: AND ((USER-AGENT,bili*), (NOT,((DOMAIN-SUFFIX,bilibili.com))), (NOT,((DOMAIN-SUFFIX,hdslb.com))), (NOT,((DOMAIN-SUFFIX,wo.cn))))
08:56:08.311832 Rule matched: RULE-SET Reject.list
08:56:08.313963 Disconnect with reason: Reject by rule

**Comment by kokororin** [comment]
08:56:08.311719 Sub-rule matched: AND ((USER-AGENT,bili*), (NOT,((DOMAIN-SUFFIX,bilibili.com))), (NOT,((DOMAIN-SUFFIX,hdslb.com))), (NOT,((DOMAIN-SUFFIX,wo.cn))))
08:56:08.311832 Rule matched: RULE-SET Reject.list
08:56:08.313963 Disconnect with reason: Reject by rule

**Comment by lhie1** [comment]
已修复
