### ISSUE TITLE
*.igexin.com 被Reject导致 Aqara 智能家居app不可用

### ISSUE THREAD

**Issue by DeltaXrayDelta** [lhie1/Rules#350]
![image](https://user-images.githubusercontent.com/53411520/80179792-d7312e00-8633-11ea-8496-526a57f5b997.png)
复现：AdBlock - AdGIF 后 Aqara 无法查找设备；AdBlock - Direct 后恢复正常
建议不要一刀切屏蔽所有 *.igexin.com 域名

**Comment by lhie1** [comment]
OK
