### ISSUE TITLE
shadowrocket规则 bilibili误配置为了asiantv，导致走了代理

### ISSUE THREAD

**Issue by wrlssqi** [lhie1/Rules#354]
bilibili部分为

 > Bilibili
USER-AGENT,bili*,AsianTV
USER-AGENT,Bilibili*,AsianTV
DOMAIN-SUFFIX,acg.tv,AsianTV
DOMAIN-SUFFIX,acgvideo.com,AsianTV
DOMAIN-SUFFIX,b23.tv,AsianTV
DOMAIN-SUFFIX,biliapi.com,AsianTV
DOMAIN-SUFFIX,biliapi.net,AsianTV
DOMAIN-SUFFIX,bilibili.com,AsianTV
DOMAIN-SUFFIX,biligame.com,AsianTV
DOMAIN-SUFFIX,biligame.net,AsianTV
DOMAIN-SUFFIX,bilivideo.com,AsianTV
DOMAIN-SUFFIX,hdslb.com,AsianTV
DOMAIN-SUFFIX,im9.com,AsianTV

**Comment by LambdaYH** [comment]
bilibili有港澳台区的

**Comment by wrlssqi** [comment]
> 
> 
> bilibili有港澳台区的

但是shadowrocket应该是不支持AsianTV这种自定义的字符吧？我没找到小火箭可以像clash那样使用之前定义的代理名称的方法。小火箭支持的路由方式应该只有reject, direct proxy吧？

**Comment by LambdaYH** [comment]
> > bilibili有港澳台区的
> 
> 但是shadowrocket应该是不支持AsianTV这种自定义的字符吧？我没找到小火箭可以像clash那样使用之前定义的代理名称的方法。小火箭支持的路由方式应该只有reject, direct proxy吧？

抱歉，没用过小火箭

**Comment by 123456qewret** [comment]
clash可以在里面选择是domestic还是proxy 小火箭不行 可以点击“编辑配置”、“替换策略”进行查找替换

**Comment by wrlssqi** [comment]
> 
> 
> clash可以在里面选择是domestic还是proxy 小火箭不行 可以点击“编辑配置”、“替换策略”进行查找替换

原来还有这种便捷的方法，之前没用过这个功能。。。非常感谢！
