### ISSUE TITLE
关于cpu.baidu.com

### ISSUE THREAD

**Issue by 1-1-2** [lhie1/Rules#373]
你好，最近开始使用lhie1/clash规则。
家里人使用`魅族资讯`APP看短视频时，发现有好多视频都打不开。
打开日志发现，视频放在`cpu.baidu.com`域名下的api里，而这个域名在adblock部分，打开网站主页标题是”最资讯“
虽然我也不太待见这类平台，但这貌似应该是个正常的资讯平台，目前也已经手动前置direcet了。
但还是很好奇这个网站有没有什么黑历史

**Comment by lhie1** [comment]
OK
