### ISSUE TITLE
macOS地图及相关服务不可用的问题

### ISSUE THREAD

**Issue by Chandler-Lu** [lhie1/Rules#382]
https://github.com/lhie1/Rules/blob/ed8b20bb938dc14f49aee36e3f57ac43bc8f60f8/Clash/Rule.yaml#L8538
该规则与macOS地图服务相关，走proxy将导致地图路径规划不可用，日历事项的位置功能不可用，建议直连，谢谢

**Comment by lhie1** [comment]
OK
