### ISSUE TITLE
请求把Akamaiedge旗下CDN域名添加到Apple Service规则下解决苹果地图偏移

### ISSUE THREAD

**Issue by xxxo0o** [lhie1/Rules#388]
我发现在macOS下使用系统自带的地图App，如果不手动直连akamaiedge.net, akadns.net, edgekey.net等Akamai旗下等CDN和DNS域名（所有地址维基百科Akamai Technology条目有列出），则会加载海外版地图，看大陆地图是定位漂移+没有详细地标坐标等状态。希望作者可以把这些域名收录进苹果服务等规则中。
感谢。

**Comment by lhie1** [comment]
将这些地址加到Apple.list 有失公正（

**Comment by imkaihao** [comment]
添加规则com.apple.geod走直连即可
`PROCESS-NAME,com.apple.geod,DIRECT`

**Comment by xxxo0o** [comment]
> 添加规则com.apple.geod走直连即可
> `PROCESS-NAME,com.apple.geod,DIRECT`
好的我去试试

**Comment by xxxo0o** [comment]
好的，我去试试
