### ISSUE TITLE
关于quantumult的rewrite

### ISSUE THREAD

**Issue by idenpa** [lhie1/Rules#39]
因为手机设置区域为中国 所以safari的搜索引擎为google.cn 更新了规则发现并不能自动替换为Google.com 请问是我的操作有问题还是需要额外的操作呢？
app：quantumult ios10.3.3

**Comment by Fndroid** [comment]
more-accessibility-rewrite google cn

**Comment by idenpa** [comment]
我有自行添加rewrite规则，只是想问问，是由于我的操作失误导致规则的rewrite没有效果，还是quantumult规则就不包含这个规则
使用了Quantumult.conf和Quantumult_URL.conf
