### ISSUE TITLE
bilibili直播使用新cdn    smtcdns.net

### ISSUE THREAD

**Issue by wrlssqi** [lhie1/Rules#393]
b站直播使用了新的cdn域名 smtcdns.net，规则匹配为others。如果others走proxy，则会误将b站直播走代理

**Comment by wrlssqi** [comment]
看了下似乎是bilibili的英雄联盟直播用了这个cdn。看了一下其它几个b站直播，还是bilivideo的域名

**Comment by lhie1** [comment]
OK
