### ISSUE TITLE
游戏里的视频广告屏蔽了域名还是会播放视频

### ISSUE THREAD

**Issue by lupin92** [lhie1/Rules#40]
卡通农场里的电影票，看完给奖励，
屏蔽了流量几M的域名后还是播放视频，
类似的广告地址也屏蔽了几段，
vungle.com
adconoly.net
可是视频还是会播放，你有兴趣搞一下吗啊 ？

**Comment by lupin92** [comment]
adconoly.net
屏蔽后有的时候就不出现电影票了
视频却照常播放

**Comment by lhie1** [comment]
意思是要屏蔽游戏里的广告视频？

**Comment by lupin92** [comment]
是的，报纸那里，有的玩家有电影票，点开看完有奖励，可是屏蔽流量几M那个还是没用…

lhie1 <notifications@github.com>于2018年5月7日 周一上午1:05写道：

**Comment by lhie1** [comment]
@lupin92 可是屏蔽了你就没法获得奖励了

**Comment by lupin92** [comment]
有个下架的mountain goat mountain屏蔽之后他说视频错误，照样给奖励。但这个就是屏蔽不了。

lhie1 <notifications@github.com>于2018年5月7日 周一上午1:09写道：

**Comment by lhie1** [comment]
@lupin92 这种自己能抓就抓吧 我不管

可以尝试利用正则匹配后面的字段屏蔽

**Comment by lupin92** [comment]
好的谢谢

lhie1 <notifications@github.com>于2018年5月7日 周一上午1:14写道：
