### ISSUE TITLE
unsupported rule type RULE-SET

### ISSUE THREAD

**Issue by lichuncat** [lhie1/Rules#404]
这次lhie1.yaml的变动比较大，之前是可以适用在rixcloud的，这次不行了，opwnwrt上的openclash报以下错误。

time="2020-09-09T19:24:18+08:00" level=fatal msg="Parse config error: rules[3] [RULE-SET,Reject,AdBlock] error: unsupported rule type RULE-SET"
2020-09-09 19:24:12 OpenClash Can Not Start, Try Use Backup Rules Start Again

有什么解决方法吗?

**Comment by lhie1** [comment]
OpenClash 作者一会儿会出一个新版本的release 进行适配，请稍等
