### ISSUE TITLE
Feature Reuqest: UPDATE DL SUBSCRIBE LINK

### ISSUE THREAD

**Issue by willin** [lhie1/Rules#408]
![7444FFF461CC8FF628E4DFEB495C9709](https://user-images.githubusercontent.com/1890238/93057993-571e6a00-f6a1-11ea-84e5-1c7cd7babd3b.jpg)

AFTER UPDATE TO  CORE 1.0

```
https://dler.cloud/subscribe/xxx?clash=vmess&noarea=cn
```

**Comment by lhie1** [comment]
Use Clash Pro

**Comment by willin** [comment]
ClashX 
<img width="472" alt="图片" src="https://user-images.githubusercontent.com/1890238/93075423-59d88980-f6b8-11ea-96c0-b442ccdf274b.png">

**Comment by lhie1** [comment]
请使用带有Clash Premium Core 的ClashX Pro
