### ISSUE TITLE
iOS网易云音乐5.1.1 开屏广告去除失败

### ISSUE THREAD

**Issue by justforadblock** [lhie1/Rules#42]
如题。

**Comment by justforadblock** [comment]
@lhie1   你好，请问为什么直接关闭了呀，广告确实存在。

**Comment by lhie1** [comment]
@justforadblock 哪存在？

**Comment by justforadblock** [comment]
@lhie1  我用的是这一份规则，用surge，订阅之后，开启Mitm和url-rewrite, 开启云音乐app，还是存在开屏广告

**Comment by justforadblock** [comment]
@lhie1  https://mega.nz/#!Mm5V0TDC!Q_bR4Wfr7cJtg5d2berR5ifNZsWyx8HwlJ3gmJhIVBI
 我拍了个视频，你看看。

**Comment by justforadblock** [comment]
@lhie1  你好，视频能看到吗？

**Comment by lhie1** [comment]
@justforadblock 可以 但是你的操作原因，重新导入规则安装并信任证书

4B 开头的证书才正确
