### ISSUE TITLE
应用 shadowrocket 规则后会导致一些 iOS 应用无法加载

### ISSUE THREAD

**Issue by meldonization** [lhie1/Rules#51]
应用： 京东金融，掌上生活
现象：应用页面无法加载，或者提示网络繁忙。然而在同样的条件下，使用 shadowrocket 自带的规则就没有上述问题

**Comment by lhie1** [comment]
@meldonization 证书

**Comment by meldonization** [comment]
不是证书的问题，证书已经添加并信任了
