### ISSUE TITLE
iShows TV的图片只有在全局下才能显示

### ISSUE THREAD

**Issue by wrong5210** [lhie1/Rules#52]

**Comment by wrong5210** [comment]
还有iShowsMovies也一样 列表和发现板块的图都显示的很慢
希望把两个app和trakt.tv网页加入代理

**Comment by lhie1** [comment]
可以提供 UA 或 URL 吗？

**Comment by wrong5210** [comment]
不知道UA URL是哪个 我用小火箭把域名
sinatra.ishowsapp.com
data.flurry.com
加入代理之后就可以显示图片了
trakt.tv应该就是这个域名没测试

**Comment by lhie1** [comment]
已添加
