### ISSUE TITLE
微信公众号内图片有问题

### ISSUE THREAD

**Issue by ldldlr** [lhie1/Rules#57]
微信的公众号图片，以及在微信内浏览新表情包时图片显示都有问题，日志看了都是direct，应该是mmbiz.qpic.cn这个，默认规则是判断user agent走的直连，我把这条删除后用final直连问题仍然存在。切换到其他规则倒是没碰到这个问题，关闭代理也不会有问题，不清楚问题是出在哪里了……另外，微博国际版偶尔会出现部分图片不显示。

**Comment by ldldlr** [comment]
ota更新rule后微信这个问题消失了……尴尬……但是今天试了很久都存在，而且规则我是前几天刚刚更新过，看下来这部分相关的规则没有变化啊……

**Comment by ldldlr** [comment]
微博国际版的问题还是存在的……不知道什么原因

**Comment by richars** [comment]
同样存在这个问题

**Comment by richars** [comment]
刚刚更新规则，微信里好像可以了，知乎里的图片还是打不开

**Comment by lhie1** [comment]
证书
