### ISSUE TITLE
Rules/Auto/URL Rewrite.conf 文件中HTTP状态码有误？

### ISSUE THREAD

**Issue by WangYue7477** [lhie1/Rules#61]
Rules/Auto/URL Rewrite.conf 文件的第四行
^https?://(www.)?google.cn/search https://www.google.com/search 307
状态码307在surge中会报错，改成302就可以运行。

**Comment by lhie1** [comment]
@WangYue7477 Surge 不支持  307

**Comment by lhie1** [comment]
@lhie1 Surge 2 不支持

**Comment by WangYue7477** [comment]
感谢大佬回复
