### ISSUE TITLE
百度知道百科等打开css样式缺失

### ISSUE THREAD

**Issue by ASIjacket** [lhie1/Rules#67]
知道和百科打开后没有样式，字体硕大，由于使用手机，无法确认是不是样式表缺失的问题，直连后恢复。

**Comment by lhie1** [comment]
证书

**Comment by TomatoFryEggs** [comment]
@lhie1 已经添加了证书，仍有问题。

**Comment by TomatoFryEggs** [comment]
@ASIjacket 原来是需要去【关于本机】里面信任证书。
@lhie1 建议增加此教程到readme。

**Comment by lhie1** [comment]
@TomatoFryEggs 使用手册没写吗？
