### ISSUE TITLE
Surge下media.nintendo.com打不开

### ISSUE THREAD

**Issue by brydio** [lhie1/Rules#72]
Request URL: http://media.nintendo.com/nintendo/bin/ngurbp8cey8VPZD82jo_lpTz3nsJVqBF/Ewg9feRKcqo7VrawVLrTxwElWkIOys5Q.jpg
Request Method: GET
Status Code: 408 Request Time-out
Remote Address: 127.0.0.1:8888
Referrer Policy: no-referrer-when-downgrade

Surge里面没有该记录的DNS解析记录
![image](https://user-images.githubusercontent.com/3771879/41408055-050aba96-7004-11e8-8b4d-41d3217a223a.png)
![image](https://user-images.githubusercontent.com/3771879/41408089-1bd865ac-7004-11e8-80e0-eddd12ed577b.png)

**Comment by lhie1** [comment]
应该是这个网站本身的问题
