### ISSUE TITLE
Shadowrocket下使用规则无法去除Spotify和Youtube APP广告

### ISSUE THREAD

**Issue by FrankZhang002** [lhie1/Rules#74]
使用规则之后，Spotify是广告大部分都不能去除，Youtube是广告部分可以去除

请教一下大家是如何去除Spotify和Youtube的广告？有没有什么规则？

**Comment by lhie1** [comment]
没有 Spotify 和 Youtube 的去广告规则

**Comment by alanhg** [comment]
> 没有 Spotify 和 Youtube 的去广告规则

没法规则屏蔽的话，只能购买会员了
