### ISSUE TITLE
墙洞的网址变了吗，无法打开网页了 

### ISSUE THREAD

**Issue by MrMessy77** [lhie1/Rules#75]

**Comment by lhie1** [comment]
@MrMessy77 主站受到DNS污染（在国内无法直接连接），导致国内直连订阅失败

请订阅用户手动将软件内的订阅地址修改：“xn--nos809b.com” -> “api.qiangdong.xyz”

Surge 托管用户不需要操作（自动迁移）

镜像站（临时）：
api.qiangdong.xyz
ss.qiangdong.xyz

**Comment by MrMessy77** [comment]
好的，谢谢
