### ISSUE TITLE
请求两条规则更新

### ISSUE THREAD

**Issue by icylogic** [lhie1/Rules#79]
- REJECT ^https?://61.129.70.132
  理由：可能是运营商劫持之类的，会在网页底部出现广告例如，http://61.129.70.132/vsd18/m/vkey04.htm 
- HOST-SUFFIX,webqxs.com,DIRECT
  理由：目前 *.webqxs.com 可直连(新加坡阿里云)

**Comment by lhie1** [comment]
done
