### ISSUE TITLE
有关 Apple 相关代理设置问题

### ISSUE THREAD

**Issue by zesming** [lhie1/Rules#83]
Hello，

我看通过 Workflow 生成的 conf 里面有关 Apple 的请求都是 DIRECT 的，某些时候我这边需要将 Apple 的请求都走代理，除了直接改 conf，把 DIRECT 改成 PROXY 以外，有没有什么好一点的方法统一修改或者切换？

谢谢~

**Comment by lhie1** [comment]
请看使用手册和 Workflow 的选项
2018年7月25日 +0800 09:52 zesming <notifications@github.com>，写道：

**Comment by zesming** [comment]
经过一下午的研究，已经搞定了，多谢~
