### ISSUE TITLE
新版Quantumult如何隐藏VPN图标？

### ISSUE THREAD

**Issue by reaCodes** [lhie1/Rules#84]
以前推特上有个朋友告诉我在Safari里输入一条命令就能隐藏了，找不到信息了。

**Comment by DrayChou** [comment]
Q：如何隐藏状态栏VPN标记？
A：VPN标志隐藏开关:
QuantumultX：点右下角logo/点右上角.../0.0.0.0/31
Quantumult：更多/附加功能/Exclude Routers 0/31
