### ISSUE TITLE
刚刚使用了规则发现shadowrocket版可以屏蔽优酷广告，quantumult无法屏蔽

### ISSUE THREAD

**Issue by jsnjycwyz** [lhie1/Rules#85]
quantumult的两个规则都订阅了，还是无法屏蔽优酷广告，但shadowrocket可以，不知道是不是规则有出入

**Comment by Freedomisgood** [comment]
shadowrocketR好像都无法屏蔽优酷视频广告啊，请问该使用哪个ACL文件啊。安卓

**Comment by lhie1** [comment]
1. 关于这个问题已经解释过原因

2.这个项目与安卓无关，无法解答
