### ISSUE TITLE
Mac 版搜狗输入法云选词被屏蔽

### ISSUE THREAD

**Issue by zesming** [lhie1/Rules#86]
早上打字的时候发现输入的正确率好低，仔细观察了下是云选词没有了。

打开 Surge Dashboard 看到了 SogouServices 里面的 http://get.sogou.com/q 命中了 DOMAIN-SUFFIX get.sogou.com,REJECT 规则。
![image](https://user-images.githubusercontent.com/7224035/43374991-04c16d64-93e5-11e8-9d13-652284ab409a.png)

找到配置文件中的相关规则，注释掉就好使了。

建议可以看下这个是否是被误伤的。

**Comment by lhie1** [comment]
已修复，谢谢
