### ISSUE TITLE
pixiv 被直连

### ISSUE THREAD

**Issue by avsdfag** [lhie1/Rules#99]
使用 JSBox  更新 Quantumult 规则后 pixiv 打不开，检查发现分流中有 2 条 pixiv.net 的规则：
![img_0eb68d9f845a-1](https://user-images.githubusercontent.com/29289305/45597941-59904f80-ba06-11e8-9b58-f0f67316c79d.jpeg)
删掉第二条 Domestic 规则后 pixiv 恢复正常。

建议删除这些规则：
https://github.com/lhie1/Rules/blob/b3d2857680e13516e5739ea33ace03b5cec1f096/Auto/DIRECT.conf#L215
https://github.com/lhie1/Rules/blob/5c6d9e297ed357131bba9b382700170c86aae97a/Shadowrocket.conf#L6269
https://github.com/lhie1/Rules/blob/980f9ae238bba1a4dfb0d43dce9f1f9601656508/Surge.conf#L6301

**Comment by lhie1** [comment]
Done
